import glob
import json
import mimetypes
import os
import subprocess


def main():
    subprocess.check_call(["pnpm", "run", "build"])

    with open("src/gen-site.h", "w") as dst:
        dst.write(
            "#ifndef SITE_H_\n"
            "#define SITE_H_\n"
            "/* This file is automatically generated by build-site.py */\n"
            "\n"
        )

        raw = bytearray()

        dst.write(
            "struct site_entry {\n"
            "  const char* name;\n"
            "  size_t offset;\n"
            "  size_t length;\n"
            "  const char* type;\n"
            "  const char* encoding;\n"
            "};\n"
            "\n"
            "static const struct site_entry site_table[] = {\n"
        )

        for name in glob.iglob("dist/**", recursive=True):
            if os.path.isfile(name):
                (type, encoding) = mimetypes.guess_type(name)

                with open(name, "rb") as src:
                    fb = src.read()
                    offset = len(raw)
                    length = len(fb)
                    raw.extend(fb)

                fields = [
                    # JSON string encoding is close enough to C for our purposes.
                    json.dumps(name.removeprefix("dist")),
                    str(offset),
                    str(length),
                    json.dumps(type),
                    json.dumps(encoding) if encoding else "NULL",
                ]
                dst.write("  {" + ", ".join(fields) + "},\n")

        dst.write("  {NULL, 0, 0, NULL, NULL}")
        dst.write("};\n\n")

        dst.write("static const uint8_t site_data[] = {\n")

        for i in range(0, len(raw)):
            if i % 12 == 0:
                if i > 0:
                    dst.write(",\n")
                dst.write("  ")
            else:
                dst.write(", ")

            dst.write(f"0x{raw[i]:02x}")

        dst.write("\n};\n\n")

        dst.write("#endif /* SITE_H_ */\n")


main()
